services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: symfony_php
    volumes:
      - ./symfony:/var/www/html
    depends_on:
      - db
      - selenium
    # Перезапускать контейнер автоматически при сбоях
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: 5K1v5&SA3|H{
      POSTGRES_DB: test_database
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      # Монтируем тот же код в /var/www/html
      - ./symfony:/var/www/html
      # Подключаем конфиг Nginx
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chromium:latest
    # или selenium/standalone-firefox:latest
    ports:
      - "4444:4444"